title: Phantom
email: youremailaddress@gmail.com
description: The Jekyll version of the Phantom theme by HTML5 UP.
baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: /assets/potrait1.jpg
font-awesome-icon-logo:

